"""
generate_embedded_logos.py
--------------------------
Lee el Logo.png de Cuerpo de Bomberos de Placilla desde la carpeta de este script
y genera embedded_logos.py con los bytes embebidos, para que PyInstaller los incluya
directamente dentro del ejecutable y no dependan de un archivo externo.

Ejecución:  python generate_embedded_logos.py [ruta_al_logo.png]

Si no se pasa ruta, intenta leer Logo.png en la misma carpeta.
"""
import os
import sys

def generate(logo_path=None):
    if logo_path is None:
        logo_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'Logo.png')

    if not os.path.isfile(logo_path):
        print(f"ERROR: No se encontró el logo en: {logo_path}")
        print("Coloca el Logo.png de Placilla junto a este script y vuelve a ejecutar.")
        sys.exit(1)

    with open(logo_path, 'rb') as f:
        data = f.read()

    size_kb = len(data) / 1024
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'embedded_logos.py')

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("# This file is AUTO-GENERATED by generate_embedded_logos.py. Do not edit manually.\n")
        f.write("# Logo de Cuerpo de Bomberos de Placilla – embebido en el ejecutable.\n\n")
        f.write(f"LOGO_PLACILLA_PNG = {repr(data)}\n")

    print(f"embedded_logos.py generado correctamente.")
    print(f"  Fuente  : {logo_path}")
    print(f"  Tamaño  : {size_kb:.1f} KB ({len(data)} bytes)")
    print(f"  Salida  : {out_path}")

if __name__ == '__main__':
    path = sys.argv[1] if len(sys.argv) > 1 else None
    generate(path)
