name: SisBom
options:
  bundleIdPrefix: com.misisbom
  objectVersion: 56
  deploymentTarget:
    iOS: "15.0"
targets:
  SisBom:
    type: application
    platform: iOS
    sources:
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Resources
      - path: SisBomApp.swift
      - path: Assets.xcassets
      - path: GoogleService-Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.misisbom.sisbom
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        ENABLE_USER_SCRIPT_SANDBOXING: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "SENTINEL ONE"
        CFBundleShortVersionString: "2.1.4"
        CFBundleVersion: "214"
        UILaunchScreen: {}
        UIBackgroundModes:
          - fetch
          - remote-notification
          - audio
          - location
        NSLocationWhenInUseUsageDescription: "SENTINEL ONE requiere acceso a su ubicación para calcular distancias a emergencias y coordinar al personal."
        NSLocationAlwaysAndWhenInUseUsageDescription: "SENTINEL ONE requiere acceso a su ubicación para alertas de despacho y seguimiento de emergencias."
        NSCameraUsageDescription: "SENTINEL ONE requiere acceso a la cámara para adjuntar fotografías en reportes y bitácora de emergencias."
        NSPhotoLibraryUsageDescription: "SENTINEL ONE requiere acceso a la galería para adjuntar imágenes a reportes de servicio y bitácora."
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            UIPrerenderedIcon: false
          CFBundleAlternateIcons:
            SB-CBPL-OH:
              CFBundleIconFiles:
                - SB-CBPL-OH
              UIPrerenderedIcon: false
            PRUEBA:
              CFBundleIconFiles:
                - PRUEBA
              UIPrerenderedIcon: false
